version: '3'
services:
  reactFront:
    image: react-front
    container_name: reactFront
    ports:
      - "3020:3000"
      - "9220:9229"
    volumes:
      - ../react-frontend:/usr/src
  nodeBack:
    image: node-back
    container_name: nodeBack
    ports:
      - "3050:3000"
      - "3051:3001"
      - "9229:9229"
    tty: true
    volumes:
      - ../node-backend:/usr/src
    links:
     - db:database
  db:
    container_name: postgres-db
    image: postgres:9.6
    restart: "no"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-db-fiuba:/var/lib/postgresql/data

volumes:
  postgres-db-fiuba: