# latest official node image
FROM node:10.15.3

MAINTAINER Nicolas Araya <naraya@cys.com.ar>

RUN npm install --verbose  --global nodemon
RUN npm install --verbose --global sequelize sequelize-cli pg
RUN mkdir -p /usr/src

WORKDIR /usr/src

EXPOSE 3000
EXPOSE 3001
EXPOSE 9229 

CMD [ "npm","run", "start-dock" ]